apiVersion: apps/v1
kind: Deployment 
metadata:
  name: httpd-frontend
  labels:
    name: test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: test-deploy
  template:
    metadata:
      name: httpd-frontend
      labels: 
        name: test-deploy
    spec:
      containers:
        - name: alpine
          image: httpd:2.4-alpine
