apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
  labels:
    app: myapp
    type: frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx