apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 500Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

#pvc with storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 500Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage